# Generated by Django 5.0.5 on 2024-05-08 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0002_remove_questionsmodel_answer_to_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsmodel',
            name='answer_option',
            field=models.CharField(default='a', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionsmodel',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameapp.optionsmodel'),
        ),
    ]
