# Generated by Django 5.0.5 on 2024-05-08 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0003_questionsmodel_answer_option_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optionsmodel',
            old_name='options',
            new_name='option',
        ),
    ]
