# Generated by Django 5.0.5 on 2024-05-08 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0004_rename_options_optionsmodel_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='answered_questions',
            new_name='attempted_questions',
        ),
    ]
