# Generated by Django 5.0.5 on 2024-05-08 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0005_rename_answered_questions_customuser_attempted_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsmodel',
            name='answer',
        ),
    ]
