# Generated by Django 5.0.5 on 2024-05-08 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0006_remove_questionsmodel_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionsmodel',
            old_name='question',
            new_name='question_text',
        ),
    ]
