# Generated by Django 5.0.5 on 2024-05-09 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0007_rename_question_questionsmodel_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsmodel',
            name='answer_pk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameapp.optionsmodel'),
        ),
    ]
