# Generated by Django 5.0.5 on 2024-05-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0008_questionsmodel_answer_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsmodel',
            name='answer_text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
