# Generated by Django 5.0.5 on 2024-05-09 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0009_questionsmodel_answer_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsmodel',
            name='answer_pk',
        ),
    ]
